version: '3.8'
services:

  nginx:
    image: nginx:latest
    container_name: fast_api_app_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    links:
      - fast_api

  redis:
    image: redis:7
    container_name: redis

  fast_api:
    build:
      context: .
    container_name: fast_api_app
    env_file:
      - .env
    depends_on:
      - redis
    # ports:
    #   - 8000:8000




